steps:

  # ---------
  # Update the flex template
  # ---------

  - id: "update flex-template"
    waitFor: ['-']
    name: "gcr.io/cloud-builders/gcloud"
    args: [
      "mvn clean package -PtemplatesRun" 
      "-DskipTests" 
      "-DprojectId=$PROJECT"
      "-DbucketName=${_TEMPLATE_BUCKET}"
      "-Dregion=us-central1"
      "-DjobName=cloud-pubsub-to-gcs-text-flex-job" 
      "-DtemplateName=Cloud_PubSub_to_GCS_Text_Flex_w_attrs" 
      "-Dparameters=inputTopic={$_INPUT_TOPIC},inputSubscription={$_INPUT_SUBSCRIPTION},outputDirectory=${_OUTPUT_DIRECTORY},userTempLocation=${_USER_TEMP_LOCATION},outputFilenamePrefix=${_OUTPUT_FILENAME_PREFIX}"
      "-f v2/googlecloud-to-googlecloud"
      ]

timeout: 1200s

substitutions:
  _TARGET_PROJECT_ID: onx-dw-raw
  _TEMPLATE_BUCKET: gs://onx-flex-templates
  _TEMPLATE_PATH: /templates/dev/${_PR_NUMBER}/onx_dw_beam_pipelines.json
  _TEMPLATE_IMAGE: us-central1-docker.pkg.dev/${_TARGET_PROJECT_ID}/onx-dw-beam-pipelines/dev/flex:${_PR_NUMBER}
  _SDK_IMAGE: us-central1-docker.pkg.dev/${_TARGET_PROJECT_ID}/onx-dw-beam-pipelines/dev/sdk:${_PR_NUMBER}
  _CORE_IMAGE: us-central1-docker.pkg.dev/${_TARGET_PROJECT_ID}/onx-dw-beam-pipelines/dev/core:${_PR_NUMBER}
options:
    dynamic_substitutions: true
